### ISSUE TITLE
Swift4.2 update

### ISSUE THREAD

**Issue by Michele404** [Skyscanner/SkyFloatingLabelTextField#238]
Update to 4.2 please

**Comment by k0nserv** [comment]
I've just released 3.6.0 which supports Swift 4.2

**Comment by newmanw** [comment]
Still getting a warning in xcode to convert to Swift 4.2 when trying to use version 3.6.0.

![screen shot 2019-01-28 at 10 11 37 am](https://user-images.githubusercontent.com/3382274/51853276-27acc500-22e5-11e9-9231-353ed088e9b3.png)

**Comment by k0nserv** [comment]
Super odd... It should be fine and the syntax is 4.2 compatible. It still compiles I assume?

**Comment by newmanw** [comment]
After a little more research it looks like xcode is really bad at recognizing when multiple versions of swift are supported:

![screen shot 2019-01-28 at 10 16 39 am](https://user-images.githubusercontent.com/3382274/51853615-f2ed3d80-22e5-11e9-99f6-c1aa268f30af.png)

Is there any way to "force" xcode to ignore this type of thing, would be nice not to have the "you need to update your swift projects warning"

**Comment by k0nserv** [comment]
Try

```ruby
post_install do |installer|
  installer.pods_project.targets.each do |pod_target|
    pod_target.build_configurations.each do |config|
      if pod_target.name == 'SkyFloatingLabelTextField'
        config.build_settings['SWIFT_VERSION'] = '4.2'
      end
    end
  end
end
```

**Comment by newmanw** [comment]
My swift version is already set to 4.2.  This still doesn't prevent xcode from seeing code that is not compat (the conde in your else statement) with swift 4.2 and thinking it needs to be converted.  Since that code will not run its not a big deal, just more fun with swift and xcode.

**Comment by k0nserv** [comment]
And even forcing the target to 4.2 doesn't make Xcode stop warning?

**Comment by newmanw** [comment]
Correct.  Xcode is picking up code that is not compat with 4.2 and it wants to update that code.

**Comment by k0nserv** [comment]
That sucks :( Don't think there's anything we can do then
